"use strict";
const q=(id,prompt,options,answer,explanation,hint="تذكّر ما تعلمته في البطاقة أعلاه.",type="choice")=>({id,prompt,options,answer,explanation,hint,type});
const lesson=(id,title,pages,focus,vocab=[],grammar="",question=null)=>({id,title,pages,focus,vocab,grammar,question});
const COURSE={
  modules:[
    {id:"welcome",title:"Welcome: Back to school",pages:"10–15",icon:"🎒",lessons:[
      lesson("w1","لغة الصف",[10,11],"فهم تعليمات الصف وتنفيذها",["Hold up your drawing","Tidy up","Put up your hand","Take out your pencil"],"Imperatives",q("w1q","اختر معنى Tidy up.",["رتّب المكان","افتح الكتاب","ارفع يدك"],"رتّب المكان","Tidy up تعني رتّب المكان.")),
      lesson("w2","قصة حقيبة Lily",[12],"السؤال عن الأشياء والأسماء",["crayons","colouring pencils","teddy","ball"],"What’s this? / What’s your name?",q("w2q","What’s your name?",["My name’s Lily.","This is a pen.","They are crayons."],"My name’s Lily.","نجيب عن الاسم بـ My name’s...")),
      lesson("w3","الأشياء والأعداد 11–20",[13,14,15],"المفرد والجمع والعد",["eleven","twelve","thirteen","fourteen","twenty"],"This/That is… These/Those are…",q("w3q","اختر الجملة الصحيحة لعدة أقلام قريبة.",["These are pens.","This is a pen.","That is a pen."],"These are pens.","These للجمع القريب."))]},
    {id:"u1",title:"Unit 1: It’s a happy day!",pages:"16–27",icon:"🌞",lessons:[
      lesson("u1l1","1. المفردات والقواعد",[16,17],"الروتين اليومي والإثبات والنفي",["get up","pray","have breakfast","go to school","have art lessons","play","have lunch","do homework","have dinner","go to bed"],"I play / don’t play. We have / don’t have lunch.",q("u1l1q","We ___ have art lessons today.",["don’t","doesn’t","isn’t"],"don’t","نستخدم don’t مع We.")),
      lesson("u1l2","2. قصة Atomic is colourful",[18,19],"قراءة القصة والقيمة",["paint","paintbrush","flowers","clean"],"Affirmative and negative sentences",q("u1l2q","ما اللون الناتج من الأزرق والأصفر؟",["green","red","white"],"green","Blue and yellow make green.")),
      lesson("u1l3","3. فترات اليوم",[20],"ربط الروتين بفترة اليوم",["morning","afternoon","evening","night"],"When do you…? We … in/at…",q("u1l3q","We have lunch in the ___.",["afternoon","night","morning"],"afternoon","في نموذج الكتاب: lunch in the afternoon.")),
      lesson("u1l4","4. مهارات الاستماع",[21],"إكمال إجابات عن الروتين",["Sunday","morning","afternoon","evening"],"When do you…?",q("u1l4q","When do you go to school?",["In the morning.","It is a school.","Yes, I do."],"In the morning.","السؤال When do يسأل عن الوقت.")),
      lesson("u1l5","5. فطور تقليدي ومشروع",[22],"ثقافات الإفطار ومشروع قائمة عُمانية",["Khubz Rakhal","eggs","beans","tea","toast","porridge"],"This is… / We have…",q("u1l5q","أكمل: ___ is Khubz Rakhal.",["This","These","We"],"This","نقدم طبقًا مفردًا بعبارة This is.")),
      lesson("u1l6","6. Saying the time",[23],"قراءة الساعة والحوار",["o’clock","quarter past","half past","quarter to"],"What time…? It’s…",q("u1l6q","7:30",["half past seven","quarter past seven","quarter to seven"],"half past seven","30 دقيقة تعني half past.")),
      lesson("u1l7","7. Phonics: wh / ph",[24],"تمييز الصوتين",["whale","wheel","phone","dolphin","elephant","alphabet","white"],"wh /w/, ph /f/",q("u1l7q","أي كلمة تبدأ بـ ph؟",["phone","whale","wheel"],"phone","phone تبدأ بالحرفين ph.")),
      lesson("u1l8","8. Review",[25],"مراجعة الروتين والضمائر والفترات",["get up","go to bed","pray","homework"],"I / We",q("u1l8q","___ do homework in the evening.",["I","He","She"],"I","النمط المستهدف هنا I do homework.")),
      lesson("u1l9","9. Get ready for…",[26],"قراءة صورة وكتابة كلمة واحدة",["morning","afternoon","evening","night"],"One-word answers",q("u1l9q","اكتب كلمة واحدة: In the ___. (المساء)",[],"evening","المساء = evening.","اكتب الكلمة الإنجليزية فقط.","text")),
      lesson("u1l10","10. Fun Corner",[27],"لعبة مسار تجمع مهارات الوحدة",["time","routine","wh","ph"],"Questions and answers",q("u1l10q","What time do you have breakfast?",["At seven o’clock.","It is breakfast.","Yes, breakfast."],"At seven o’clock.","نجيب عن What time بوقت."))]},
    {id:"u2",title:"Unit 2: Let’s dress up!",pages:"36–47",icon:"👕",lessons:[
      lesson("u2l1","1. الملابس ووصفها",[36,37],"وصف ما يرتديه الناس",["shirt","jumper","coat","baseball cap","hijab","jeans","tracksuit","pyjamas","slippers","trainers"],"You’re/We’re/They’re wearing…",q("u2l1q","They’re ___ trainers.",["wearing","wear","wears"],"wearing","بعد They’re نستخدم wearing.")),
      lesson("u2l2","2. The school show",[38,39],"قصة إعادة استخدام الملابس",["show","recycle","clothes","amazing"],"They’re wearing…",q("u2l2q","ما قيمة القصة؟",["Don’t be wasteful.","Sleep early.","Eat breakfast."],"Don’t be wasteful.","القصة تشجع على عدم الإسراف وإعادة الاستخدام.")),
      lesson("u2l3","3. المقتنيات والملكية",[40],"الأشياء الشخصية وألوانها",["keys","handbag","glasses","backpack","phone","computer"],"Our / Your / Their",q("u2l3q","___ glasses are blue. (نظاراتنا)",["Our","Your","Their"],"Our","Our تعني الخاصة بنا.")),
      lesson("u2l4","4. مهارات الوصف",[41],"الاستماع وتحديد الملابس والألوان",["red","purple","pink","blue"],"They’re wearing… Their…",q("u2l4q","They’re wearing hijabs. ___ hijabs are red.",["Their","Our","Your"],"Their","نستخدم Their لما يملكه هم.")),
      lesson("u2l5","5. Special days in Oman",[42],"ملابس العيد ومشروع ملصق",["Eid Al-Fitr","traditional clothes","presents","sweets","Eidiya"],"This is… / They’re wearing…",q("u2l5q","ما المناسبة المذكورة في الصفحة؟",["Eid Al-Fitr","National Day","Sports Day"],"Eid Al-Fitr","يتناول النص عيد الفطر في عُمان.")),
      lesson("u2l6","6. Asking the price",[43],"السؤال عن السعر",["rial","price","baseball cap","handbag"],"How much is this…? It’s … rials.",q("u2l6q","___ is this baseball cap?",["How much","How many","What colour"],"How much","How much للسؤال عن السعر.")),
      lesson("u2l7","7. Phonics: ear / ure",[44],"تمييز مجموعتي الأصوات",["beard","hear","vulture","picture"],"ear / ure",q("u2l7q","أي كلمة بها ure؟",["picture","hear","beard"],"picture","picture تنتهي بـ ture وفيها ure.")),
      lesson("u2l8","8. Review",[45],"مراجعة الملابس والملكية",["glasses","backpack","jeans","trainers","slippers"],"We’re/You’re/They’re + Our/Your/Their",q("u2l8q","We’re wearing coats. ___ coats are long.",["Our","Their","Your"],"Our","Our يعود على We.")),
      lesson("u2l9","9. Get ready for…",[46],"صح أو خطأ ووصف صورة",["trainers","cap","jeans","hijab","glasses","coat"],"Pre A1 practice",q("u2l9q","اختر جملة صحيحة نحويًا.",["They’re wearing trainers.","They wearing trainers.","They’re wear trainers."],"They’re wearing trainers.","الصيغة: They’re + wearing.")),
      lesson("u2l10","10. Fun Corner",[47],"لعبة وصف الملابس والألوان",["green T-shirt","clothes","colour"],"You’re wearing…",q("u2l10q","صف قميصًا أخضر.",["You’re wearing a green T-shirt.","You green wearing.","Your T-shirt wear."],"You’re wearing a green T-shirt.","نبدأ بـ You’re wearing ثم اللون والقطعة."))]},
    {id:"lb1",title:"Language Booster 1",pages:"56–57",icon:"🔢",lessons:[lesson("lb1l1","الأعداد 21–30 والعشرات",[56,57],"العد والترتيب حتى 100",["twenty-one","thirty","forty","fifty","sixty","seventy","eighty","ninety","one hundred"],"Cardinal numbers",q("lb1q","ما العدد الذي يلي twenty-nine؟",["thirty","twenty-eight","forty"],"thirty","بعد 29 يأتي 30: thirty."))]},
    {id:"math",title:"Maths: How do we measure things?",pages:"58–59",icon:"📏",lessons:[lesson("mathl1","الطول والعرض",[58,59],"استخدام mm وcm وm",["long","wide","millimetre","centimetre","metre","ruler"],"How long/wide is it? It’s …",q("mathq","كم سنتيمترًا في المتر؟",["100","10","1000"],"100","يوجد 100 centimetres في metre واحد."))]},
    {id:"u3",title:"Unit 3: Hobbies",pages:"60–71",icon:"🚲",lessons:[
      lesson("u3l1","1. الهوايات",[60,61],"وصف نشاط الغائب",["ride a bike","do karate","play video games","skateboard","watch TV","play tennis","listen to music","play basketball","read books","roller-skate"],"He/She plays. He/She doesn’t…",q("u3l1q","She ___ tennis.",["plays","play","playing"],"plays","نضيف s للفعل مع She.")),
      lesson("u3l2","2. Where’s Fatma?",[62,63],"قصة الهوايات والأوقات",["tennis","skateboard","roller-skate","picnic"],"Does she…?",q("u3l2q","ماذا تفعل Fatma عند الساعة 10؟",["She skateboards.","She watches TV.","She reads."],"She skateboards.","في القصة: She skateboards at 10 o’clock.")),
      lesson("u3l3","3. أيام الأسبوع والأسئلة",[64],"السؤال عن أنشطة الغائب",["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","weekend"],"Does he…? Yes, he does/No, he doesn’t.",q("u3l3q","Does he watch TV?",["Yes, he does.","Yes, he do.","Yes, he is."],"Yes, he does.","الإجابة القصيرة تستخدم does.")),
      lesson("u3l4","4. مهارات الجدول الأسبوعي",[65],"قراءة جدول نشاط",["weekend","Wednesday","Monday"],"He/She + activity",q("u3l4q","He ___ at the weekend.",["roller-skates","roller-skate","roller-skating"],"roller-skates","مع He نضيف s.")),
      lesson("u3l5","5. Traditional sports in Oman",[66],"سباق الهجن والقوارب الشراعية",["camel racing","dhow racing","traditional sport","kilometres"],"He/She plays… on…",q("u3l5q","أي رياضة تستخدم قوارب تقليدية؟",["dhow racing","camel racing","tennis"],"dhow racing","الـ dhow قارب شراعي تقليدي.")),
      lesson("u3l6","6. Saying how often",[67],"التعبير عن التكرار",["always","often","never"],"I always/often/never…",q("u3l6q","أي كلمة تعني أبدًا لا؟",["never","always","often"],"never","never تعني لا يحدث أبدًا.")),
      lesson("u3l7","7. Phonics: split e",[68],"أصوات i-e/a-e/o-e/u-e",["bike","cake","stone","cube","tube"],"Long vowel + silent e",q("u3l7q","أي كلمة بها i-e؟",["bike","cake","stone"],"bike","bike تحتوي i-e.")),
      lesson("u3l8","8. Review",[69],"مراجعة الهوايات والأسئلة",["tennis","TV","skateboard","books"],"Does…?",q("u3l8q","___ she play tennis?",["Does","Do","Is"],"Does","نستخدم Does مع she.")),
      lesson("u3l9","9. Get ready for…",[70],"Yes/No والتحدث من صورة",["bike","karate","music","TV"],"Pre A1 practice",q("u3l9q","He ___ books at the weekend.",["reads","read","reading"],"reads","He يأخذ فعلًا منتهيًا بـ s.")),
      lesson("u3l10","10. Fun Corner",[71],"لعبة سؤال عن الجدول",["days","activities"],"Does … on Mondays?",q("u3l10q","Does Faisal play tennis on Mondays?",["Yes, he does.","Yes, he is.","Yes, he plays?"],"Yes, he does.","نستخدم جوابًا قصيرًا بـ does."))]},
    {id:"u4",title:"Unit 4: I want to be a doctor!",pages:"80–91",icon:"👩‍⚕️",lessons:[
      lesson("u4l1","1. الوظائف والطموح",[80,81],"تسمية الوظائف",["teacher","police officer","nurse","pilot","chef","doctor","firefighter","astronaut","artist","builder"],"I want to be a/an…",q("u4l1q","I want to be ___ artist.",["an","a","the"],"an","نستخدم an قبل صوت حرف متحرك.")),
      lesson("u4l2","2. The job fair",[82,83],"قصة المهن واتباع الأحلام",["job fair","medicine","uniform","dream"],"I want to be…",q("u4l2q","ما قيمة القصة؟",["Follow your dreams.","Don’t be wasteful.","Go to bed early."],"Follow your dreams.","القيمة المكتوبة: Follow your dreams.")),
      lesson("u4l3","3. وسائل النقل",[84],"وصف الذهاب إلى العمل",["car","boat","motorbike","train","underground","bus"],"He/She goes to work by…",q("u4l3q","She ___ to work by train.",["goes","go","going"],"goes","مع She نستخدم goes.")),
      lesson("u4l4","4. مهارات المهنة والنقل",[85],"مطابقة الشخص بالعمل والنقل",["teacher","nurse","train","car"],"He’s/She’s…",q("u4l4q","___ a nurse. (هو)",["He’s","She’s","They’re"],"He’s","He’s = He is.")),
      lesson("u4l5","5. The yellow school bus",[86],"قراءة ثقافية ومشروع رسم بياني",["school bus","bus driver","students","bus stop"],"I go to school by…",q("u4l5q","ما لون حافلات المدارس في النص الأمريكي؟",["yellow","blue","red"],"yellow","النص يذكر أن جميعها صفراء.")),
      lesson("u4l6","6. Talking on the phone",[87],"محادثة هاتفية مهذبة",["phone number","call","speak"],"Can I speak to…? Who is this?",q("u4l6q","Hello, can I ___ to Emily, please?",["speak","speaks","speaking"],"speak","بعد can نستخدم الفعل الأساسي.")),
      lesson("u4l7","7. Phonics: ea",[88],"تمييز صوتي ea",["read","beach","bread","weather","head","sea"],"ea has different sounds",q("u4l7q","أي كلمتين لهما صوت ea نفسه؟",["bread / weather","read / bread","sea / weather"],"bread / weather","ea في bread وweather بالصوت القصير نفسه.")),
      lesson("u4l8","8. Review",[89],"مراجعة المهن والنقل",["car","motorbike","bus","boat"],"He/She goes…",q("u4l8q","He goes to work ___ bus.",["by","in","at"],"by","نقول by bus.")),
      lesson("u4l9","9. Get ready for…",[90],"صح أو خطأ وحديث شخصي",["artist","pilot","teacher","doctor"],"Pre A1 practice",q("u4l9q","اختر جملة صحيحة.",["I want to be a pilot.","I want be pilot.","I wants a pilot."],"I want to be a pilot.","الصيغة I want to be…")),
      lesson("u4l10","10. Fun Corner",[91],"لعبة مهنة ووسيلة نقل",["jobs","transport"],"I want to be… I want to travel by…",q("u4l10q","اختر عبارتين سليمتين.",["I want to be a nurse. I want to travel by train.","I be nurse. I travel train.","I wants nurse by train."],"I want to be a nurse. I want to travel by train.","نستخدم want to be وby قبل وسيلة النقل."))]},
    {id:"lb2",title:"Language Booster 2: Seasons",pages:"100–101",icon:"🍂",lessons:[lesson("lb2l1","الفصول الأربعة",[100,101],"تسمية الفصول ووصفها",["winter","spring","summer","autumn","cold","sunny","windy"],"What season is it? It’s…",q("lb2q","It’s windy. The trees are brown.",["autumn","summer","spring"],"autumn","الرياح والأوراق البنية تصف autumn."))]},
    {id:"social",title:"Social Studies: Important months",pages:"102–103",icon:"🗓️",lessons:[lesson("sociall1","الأشهر والميلاد",[102,103],"ترتيب الأشهر والسؤال عن الميلاد",["January","February","March","April","May","June","July","August","September","October","November","December"],"When is your birthday? It’s in…",q("socialq","أي شهر يأتي بعد June؟",["July","May","August"],"July","بعد June يأتي July."))]}
  ],
  stories:[
    {id:"atomic",module:"u1",title:"Atomic is colourful!",pages:"18–19",value:"See beauty in everything.",scenes:["Sami and Jack play tennis in the park before school. Lily and Fatma hurry to their art lesson.","Polly jumps onto the table. Blue and yellow paint spill, and Atomic becomes green and colourful.","The friends clean the floor and paint a colourful picture of Atomic."],question:q("sq1","ماذا فعل الأصدقاء بعد الفوضى؟",["They cleaned the floor.","They went to bed.","They played tennis."],"They cleaned the floor.","نظّفوا الأرضية بعد انسكاب الألوان.")},
    {id:"robot",module:"u1",title:"Welcome to Robot School!",pages:"28–31",value:"A school day can be organised and fun.",scenes:["Robot goes to school at eight o’clock.","At half past eight, the robots have English. At half past twelve, they have lunch.","At half past one, they have art. At quarter to three, they go home. Robot does homework, but robots don’t sleep!"],question:q("sq2","متى يذهب Robot إلى البيت؟",["At quarter to three.","At half past one.","At eight o’clock."],"At quarter to three.","تذكر العبارة It’s quarter to three. Now we go home.")},
    {id:"elephant",module:"u1",title:"Elephant’s Day",pages:"32–35",value:"A reading about one character’s day, not advice for every child.",scenes:["Elephant gets up in the morning, stretches and has a big breakfast.","In the afternoon, Elephant plays. In the evening, Elephant has dinner and sings.","At ten o’clock, Elephant doesn’t play or sing. Elephant goes to bed."],question:q("sq3","متى يلعب Elephant؟",["In the afternoon.","At night.","In the morning."],"In the afternoon.","في القصة يلعب الفيل بعد الظهر.")},
    {id:"schoolshow",module:"u2",title:"The school show",pages:"38–39",value:"Don’t be wasteful.",scenes:["The children prepare clothes for a school show.","Some clothes are too small, so they get an idea and reuse different clothes.","They make a colourful show and decide to recycle more clothes."],question:q("sq4","لماذا أعادوا استخدام الملابس؟",["For the school show.","For breakfast.","For a race."],"For the school show.","جهزوا عرض المدرسة." )},
    {id:"clothesgame",module:"u2",title:"The Clothes Game",pages:"48–51",value:"Friends can play creatively.",scenes:["The girls close their eyes and count to ten.","They put on a colourful mixture of clothes.","They describe coats, slippers and handbags, and find the glasses on a girl’s head."],question:q("sq5","أين كانت النظارات؟",["On her head.","In a bag.","Under the bed."],"On her head.","كانت على الرأس قرب الأذنين." )},
    {id:"dadtracksuit",module:"u2",title:"Dad’s Tracksuit",pages:"52–55",value:"Memories connect families.",scenes:["Dad shows a special book with old pictures.","In a picture, Dad is sixteen and his football team wears red tracksuits and trainers.","Dad gives the child red clothes, and they play football together."],question:q("sq6","ما لون ملابس الفريق؟",["red","green","blue"],"red","ملابس الفريق وحذاؤه أحمر." )},
    {id:"fatma",module:"u3",title:"Where’s Fatma?",pages:"62–63",value:"Have fun.",scenes:["The friends look for Fatma and follow her activity times.","She plays tennis, skateboards and roller-skates.","They find her tired under a tree and have a picnic."],question:q("sq7","أين وجدوا Fatma؟",["Under the tree.","At school.","On a boat."],"Under the tree.","وجدوها تحت الشجرة." )},
    {id:"park",module:"u3",title:"Fun at the Park",pages:"72–75",value:"Friends help each other.",scenes:["Maryam and Badriya go to the park on Friday.","Maryam’s basketball gets stuck in a tree.","Badriya uses her tennis racket to get the ball down."],question:q("sq8","بماذا أنزلت Badriya الكرة؟",["A tennis racket.","A bike.","A book."],"A tennis racket.","استخدمت مضرب التنس." )},
    {id:"camel",module:"u3",title:"The Camel Race",pages:"76–79",value:"Kind encouragement helps.",scenes:["A child watches camel racing with Dad on Saturday.","Farha stops, so the child rides a bike with a peach.","Farha follows the peach, wins the race and gets the peach."],question:q("sq9","ما الفاكهة التي شجعت Farha؟",["A peach.","An apple.","A banana."],"A peach.","كانت الفاكهة peach." )},
    {id:"jobfair",module:"u4",title:"The Job Fair",pages:"82–83",value:"Follow your dreams.",scenes:["Children meet people with different jobs at the fair.","Lisa tries ideas such as teacher, pilot and chef.","A doctor helps Lisa feel better, and Lisa wants to be a doctor."],question:q("sq10","من ساعد Lisa عندما مرضت؟",["A doctor.","A pilot.","A builder."],"A doctor.","Mrs Shahad is a doctor." )},
    {id:"jobsday",module:"u4",title:"It’s Jobs Day",pages:"92–95",value:"Every useful job matters.",scenes:["Children wear clothes for their favourite jobs.","Noora and Hamed show job clothes, but Qais wears school clothes.","Qais explains that he wants to be a teacher."],question:q("sq11","ماذا يريد Qais أن يكون؟",["A teacher.","A chef.","An astronaut."],"A teacher.","قال I want to be a teacher." )},
    {id:"beach",module:"u4",title:"A Boat to the Beach",pages:"96–99",value:"Be flexible when plans change.",scenes:["A child and Mum plan to go to the beach by train, then try a bus.","The bus stops, so they get on a boat. The boat waits, then goes.","They reach the sunny beach and later see their boat at sea."],question:q("sq12","بأي وسيلة وصلوا بعد تعطل الخطط؟",["By boat.","By underground.","By motorbike."],"By boat.","ركبوا القارب ووصلوا إلى الشاطئ." )}
  ]
};
COURSE.lessons=COURSE.modules.flatMap(m=>m.lessons.map(l=>({...l,moduleId:m.id,moduleTitle:m.title})));
COURSE.questions=COURSE.lessons.map(l=>({...l.question,lessonId:l.id,moduleId:l.moduleId,source:`Class Book p. ${l.pages.join("–")}`}));
Object.freeze(COURSE);
